from streamlit_folium import folium_static
import folium
import pandas as pd
import gpxpy
import streamlit as st
import streamlit.components.v1 as stc


def gpx_map_render():
    st.title('Mapping GPX tracks')
    st.markdown('GPXファイルをアップロードすると、経路付きの地図を表示します。')

    uploaded_file = st.file_uploader("Choose a GPX file", type='gpx')
    if uploaded_file is not None:
        # st.write(uploaded_file)

        gpx_p = gpxpy.parse(uploaded_file.getvalue().decode('utf-8'))
        gpx_list = []
        # tonlist
        for track in gpx_p.tracks:
            for i, segment in enumerate(track.segments):
                for point in segment.points:
                    gpx_list.append([point.latitude, point.longitude,
                                     point.elevation, point.time, track.name, i])
        # to pd.DataFrame
        colname = ['latitude', 'longitude',
                   'elevation', 'time', 'trackname', 'segment_no']
        df = pd.DataFrame(gpx_list, columns=colname)
        df_t = df[['latitude', 'longitude']]
        # st.map(df_t,zoom=8)

        fmap = folium.Map(
            location=(df_t.iloc[0]+df_t.iloc[-1])/2, zoom_start=10)
        folium.PolyLine(df_t).add_to(fmap)
        folium_static(fmap)

    else:
        st.markdown('#')
        st.subheader('Sample')
        with open('files/Shimanami.html') as f:
            s = f.read()
        stc.html(s,height=250)
        #st.markdown('[html](pages/Shimanami.html)')

    st.markdown(
        'Generated by [Folium](https://python-visualization.github.io/folium/)',
        unsafe_allow_html=True)


gpx_map_render()